In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
from matplotlib import pyplot as plt

In [2]:
df = pd.read_csv("data\maas.csv")

In [3]:
df.head()

,level,position,tech_stack,experience,gender,company,company_size,work_type,city,currency,salary_for_other_currency,salary_for_tl_currency
0,Middle,Back-end Developer,Php,3 - 5 Yıl,Erkek,Startup,25 - 50 Kişi,Hibrit (Ofis + Remote),İstanbul,₺ - Türk Lirası,NaN,15.000 TL - 15.999 TL
1,Junior,Front-end Developer,React,0 - 1 Yıl,Erkek,Startup,10 - 25 Kişi,Hibrit (Ofis + Remote),İstanbul,₺ - Türk Lirası,NaN,8.000 TL - 8.999 TL
2,Middle,Back-end Developer,.Net,1 - 3 Yıl,Erkek,Outsource,10 - 25 Kişi,Remote,İstanbul,₺ - Türk Lirası,NaN,15.000 TL - 15.999 TL
3,Junior,Full Stack Developer,"Java, JavaScript | Html | Css, React, React Na...",1 - 3 Yıl,Erkek,Startup,10 - 25 Kişi,Hibrit (Ofis + Remote),İstanbul,₺ - Türk Lirası,NaN,10.000 TL - 10.999 TL
4,Junior,Back-end Developer,".Net, JavaScript | Html | Css",0 - 1 Yıl,Erkek,Kurumsal,250+,Pandemi Nedeniyle; Geçici Olarak Hibrit (Ofis ...,Kocaeli,₺ - Türk Lirası,NaN,5.000 TL - 5.999 TL

In [4]:
#okunurluk için kolon isimlerini büyük harf yaptık.
df.columns = [col.upper() for col in df.columns]
df.head()

,LEVEL,POSITION,TECH_STACK,EXPERIENCE,GENDER,COMPANY,COMPANY_SIZE,WORK_TYPE,CITY,CURRENCY,SALARY_FOR_OTHER_CURRENCY,SALARY_FOR_TL_CURRENCY
0,Middle,Back-end Developer,Php,3 - 5 Yıl,Erkek,Startup,25 - 50 Kişi,Hibrit (Ofis + Remote),İstanbul,₺ - Türk Lirası,NaN,15.000 TL - 15.999 TL
1,Junior,Front-end Developer,React,0 - 1 Yıl,Erkek,Startup,10 - 25 Kişi,Hibrit (Ofis + Remote),İstanbul,₺ - Türk Lirası,NaN,8.000 TL - 8.999 TL
2,Middle,Back-end Developer,.Net,1 - 3 Yıl,Erkek,Outsource,10 - 25 Kişi,Remote,İstanbul,₺ - Türk Lirası,NaN,15.000 TL - 15.999 TL
3,Junior,Full Stack Developer,"Java, JavaScript | Html | Css, React, React Na...",1 - 3 Yıl,Erkek,Startup,10 - 25 Kişi,Hibrit (Ofis + Remote),İstanbul,₺ - Türk Lirası,NaN,10.000 TL - 10.999 TL
4,Junior,Back-end Developer,".Net, JavaScript | Html | Css",0 - 1 Yıl,Erkek,Kurumsal,250+,Pandemi Nedeniyle; Geçici Olarak Hibrit (Ofis ...,Kocaeli,₺ - Türk Lirası,NaN,5.000 TL - 5.999 TL

In [5]:
df.shape

(5030, 12)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5030 entries, 0 to 5029
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   LEVEL                      5030 non-null   object
 1   POSITION                   5030 non-null   object
 2   TECH_STACK                 5029 non-null   object
 3   EXPERIENCE                 5030 non-null   object
 4   GENDER                     5030 non-null   object
 5   COMPANY                    5030 non-null   object
 6   COMPANY_SIZE               5030 non-null   object
 7   WORK_TYPE                  5030 non-null   object
 8   CITY                       5030 non-null   object
 9   CURRENCY                   5030 non-null   object
 10  SALARY_FOR_OTHER_CURRENCY  533 non-null    object
 11  SALARY_FOR_TL_CURRENCY     4493 non-null   object
dtypes: object(12)
memory usage: 471.7+ KB

In [7]:
df.isnull().sum()

LEVEL                           0
POSITION                        0
TECH_STACK                      1
EXPERIENCE                      0
GENDER                          0
COMPANY                         0
COMPANY_SIZE                    0
WORK_TYPE                       0
CITY                            0
CURRENCY                        0
SALARY_FOR_OTHER_CURRENCY    4497
SALARY_FOR_TL_CURRENCY        537
dtype: int64

In [8]:
#her kolonun içerdiği unique değer sayısına bakıyoruz.
for col in df.columns:
    print(col, df[col].nunique())

LEVEL 3
POSITION 30
TECH_STACK 866
EXPERIENCE 7
GENDER 2
COMPANY 18
COMPANY_SIZE 6
WORK_TYPE 5
CITY 147
CURRENCY 4
SALARY_FOR_OTHER_CURRENCY 11
SALARY_FOR_TL_CURRENCY 45

In [9]:
#her kolondaki unique değerlerin neler olduğuna bakıyoruz.
for col in df.columns:
    print(col, df[col].unique())
    print(f"============================================================================================")

LEVEL ['Middle' 'Junior' 'Senior']
============================================================================================
POSITION ['Back-end Developer' 'Front-end Developer' 'Full Stack Developer'
 'Mobile Application Developer' 'Embedded Software Developer'
 'Team / Tech Lead' 'Software Development Manager' 'Game Developer'
 'Data Scientist' 'Software Architect' 'RPA Developer'
 'Computer Vision Engineer' 'QA / Test Automation Developer'
 'DevOps Engineer' 'Data Analyst' 'Data Engineer' 'CTO' 'Machine Learning'
 'Database Administrator' 'IT Specialist' 'Project & Product Manager / PO'
 'Consultant' 'R&D Engineer' 'Support Engineer' 'Business Analyst'
 'Seo Specialist' 'SAP/ABAP/ERP Developer' 'SysAdmin' 'Security'
 'Blockchain Developer']
============================================================================================
TECH_STACK ['Php' 'React' '.Net' 'Java, JavaScript | Html | Css, React, React Native'
 '.Net, JavaScript | Html | Css' 'Python, Kotlin, React Native'
 '.Net, JavaScript | Html | Css, Angular, React Native'
 'Php, JavaScript | Html | Css' 'Php, Go, JavaScript | Html | Css, Vue'
 'Swift / Objective C' 'JavaScript | Html | Css, React, Vue, Express.js'
 'JavaScript | Html | Css, Vue' 'Swift / Objective C, Flutter' 'Java' 'Go'
 'Php, Swift / Objective C' '.Net, Php, Vue' 'C / C++' 'Python'
 'Php, Angular' 'JavaScript | Html | Css' 'Node JS'
 '.Net, Vue, Angular, Flutter'
 '.Net, JavaScript | Html | Css, React, Angular' '.Net, Angular'
 '.Net, Flutter'
 '.Net, Swift / Objective C, JavaScript | Html | Css, React, React Native'
 'Php, React, Angular' 'React, Vue' '.Net, JavaScript | Html | Css, React'
 'Java, .Net, Python, JavaScript | Html | Css, React, Angular'
 'Lowcode platformlar servicenow,pega'
 'Java, .Net, Python, JavaScript | Html | Css'
 'Java, JavaScript | Html | Css' 'Angular'
 '.Net, Go, JavaScript | Html | Css' 'Java, Go, Python'
 '.Net, Python, Angular' 'Unity' 'JavaScript | Html | Css, React'
 'Php, JavaScript | Html | Css, Flutter'
 'JavaScript | Html | Css, React, Vue'
 'Java, .Net, JavaScript | Html | Css' 'Php, JavaScript | Html | Css, Vue'
 'Node.js' 'Php, Go, JavaScript | Html | Css, Vue, Angular' 'Kotlin'
 'JavaScript | Html | Css, Vue, Node.js' 'Php, Flutter' 'Java, React'
 'JavaScript | Html | Css, Angular'
 'Php, JavaScript | Html | Css, React, Vue' 'Java, .Net' 'Unity, C#'
 'sap abap' 'Java, Python' '.Net, JavaScript | Html | Css, Angular'
 'UiPath' 'React, Nodejs' 'Java, Kotlin'
 '.Net, JavaScript | Html | Css, Jquery' 'Go, Vue, Flutter' 'Ruby'
 'Go, Python' 'Flutter' 'Java, Vue' 'Php, Perl' 'Postman/SoapUı'
 'Java, .Net, JavaScript | Html | Css, React'
 'JavaScript | Html | Css, React, Angular'
 'Java, .Net, Php, Go, Ruby, Kotlin, Swift / Objective C, JavaScript | Html | Css, Flutter, React Native'
 'Java, Python, JavaScript | Html | Css, React' '.Net, Vue'
 'Php, Go, Python, Swift / Objective C, JavaScript | Html | Css, React, Vue, React Native'
 '.Net, JavaScript | Html | Css, React, React Native' '.Net, Vue, Angular'
 'Java, Kotlin, Swift / Objective C, React' '.Net, Node js' 'Php, React'
 'JavaScript | Html | Css, Vue, Flutter' 'Kotlin, JavaScript | Html | Css'
 'JavaScript | Html | Css, React, Vue, React Native'
 'Yazılım geliştirmiyorum' 'Ruby, React'
 '.Net, JavaScript | Html | Css, Angularjs,c#'
 'Java, Kotlin, Swift / Objective C' 'Python, JavaScript | Html | Css'
 'JavaScript | Html | Css, React, Nest.js'
 '.Net, Go, JavaScript | Html | Css, React, Angular' 'Python, SQL'
 'Delphi' 'Java, Go' 'Python, Ruby' 'React, React Native'
 'Python, C / C++' 'Php, JavaScript | Html | Css, Angular'
 'Java, .Net, Php, Python, Swift / Objective C, C / C++, JavaScript | Html | Css, React, Vue, Angular, React Native'
 'Java, .Net, Php, Go, Python, React, Angular, React Native, Unreal'
 'Java, Quick' '.Net, JavaScript | Html | Css, Angular, Delphi' '.Net, Go'
 'React Native' '.Net, JavaScript | Html | Css, Vue, Angular'
 '.Net, JavaScript | Html | Css, React, Vue, Angular'
 '.Net, JavaScript | Html | Css, Vue'
 '.Net, Php, C / C++, JavaScript | Html | Css' 'Python, React'
 '.Net, C / C++' 'Go, Python, Vue' 'Ruby, JavaScript | Html | Css, React'
 'Python, JavaScript | Html | Css, React' 'Java, .Net, C / C++'
 'Java, .Net, JavaScript | Html | Css, React, Vue'
 'Python, JavaScript | Html | Css, Jinja, Jquery'
 'Java, .Net, JavaScript | Html | Css, Vue, Angular'
 'JavaScript | Html | Css, Node.js' 'Oracle Apex / PL/SQL' 'Java, Php'
 'Java, Python, JavaScript | Html | Css'
 'Php, Go, JavaScript | Html | Css, Vue, Flutter' 'Swift'
 '.Net, C / C++, JavaScript | Html | Css, React' '.Net, React'
 'JavaScript | Html | Css, React Native' 'Java, React, Angular'
 'Java, Php, JavaScript | Html | Css, Vue' 'Java, .Net, Go, Kotlin' 'Vue'
 'React, NodeJS'
 'Java, Php, Go, Python, JavaScript | Html | Css, React Native'
 'Swift / Objective C, React Native' 'Php, Vue'
 'Ruby, JavaScript | Html | Css, React, React Native'
 'Java, Swift / Objective C, node' '.Net, Unity' '.Net, PL-SQL '
 '.Net, Php, JavaScript | Html | Css' '.Net, Php'
 'Kotlin, Swift / Objective C' 'Sql'
 '.Net, Php, JavaScript | Html | Css, Angular, nodejs' 'SQL'
 'JavaScript | Html | Css, Razor'
 'Java, Php, Python, JavaScript | Html | Css, React' 'Java, Unity'
 '.Net, Kotlin, JavaScript | Html | Css, Angular'
 'JavaScript | Html | Css, React, Rust' 'Java, .Net, Php, Go, Python'
 'React, Vue, Angular' '.Net, JavaScript | Html | Css, React Native'
 'JavaScript | Html | Css, React, Node.js'
 'gitlab ci,docker,openstack,grafana,Prometheus,'
 'Java, C / C++, JavaScript | Html | Css, Angular'
 '.Net, React, React Native'
 'JavaScript | Html | Css, React, React Native'
 '.Net, JavaScript | Html | Css, React, Vue, Angular, Flutter, React Native'
 '.Net, Python' '.Net, JavaScript | Html | Css, Flutter'
 '.Net, Go, JavaScript | Html | Css, React' 'Node'
 'Java, JavaScript | Html | Css, React' 'Go, Nodejs' 'C / C++, Unreal'
 'Java, Kotlin, Flutter' 'Java, Plsql'
 'Java, Python, C / C++, JavaScript | Html | Css, React, Angular'
 'Java, PL/SQL' 'Jira & confluence'
 'Java, Php, Kotlin, Swift / Objective C'
 'Java, JavaScript | Html | Css, Angular' 'Oracle PL/SQL'
 'Php, JavaScript | Html | Css, React' 'Java, React, React Native'
 '.Net, Kotlin, JavaScript | Html | Css, Vue, Angular'
 '.Net, C / C++, Unity' '.Net, Python, React, Vue, Angular'
 'Java, .Net, Go, Python, Vue' 'Java, Angular' 'It' '.Net, React, Angular'
 'Java, .Net, Apache, big data' '.Net, Python, C / C++' 'Java, C / C++'
 'Java, .Net, JavaScript | Html | Css, Bootstrap '
 'Python, React, Vue, Angular, React Native' 'Typescript'
 '.Net, JavaScript | Html | Css, React, Vue' 'ABAP'
 'Java, .Net, Php, Python' 'Php, Go, React, Vue, Flutter'
 'React, Vue, React Native' 'Java, JavaScript | Html | Css, Vue'
 'Php, Nodejs' 'Java, .Net, Python, C / C++, Unity'
 '.Net, Python, JavaScript | Html | Css, Vue'
 'Java, Kotlin, Swift / Objective C, Flutter'
 'Swift / Objective C, JavaScript | Html | Css, React, Angular, Flutter, React Native, Unity'
 'Python, Vue' 'Java, JavaScript | Html | Css, React Native'
 '.Net, Go, C / C++, JavaScript | Html | Css, Vue, Angular'
 'Java, Php, Python, JavaScript | Html | Css, Nodejs' 'Oracle'
 'Java, Kotlin, C / C++' 'JavaScript | Html | Css, Flutter, React Native'
 'Java, Php, JavaScript | Html | Css, React, Yoğunluklu js frameworks '
 'Java, .Net, Kotlin, Swift / Objective C, JavaScript | Html | Css'
 '.Net, C / C++, JavaScript | Html | Css, Vue' 'Java, React, Plsql'
 'Java, .Net, React' 'Java, JavaScript | Html | Css, Cobol '
 'Java, Go, Kotlin' '.Net, Vue, Flutter' 'Plsql '
 'Java, Php, Kotlin, JavaScript | Html | Css'
 '.Net, JavaScript | Html | Css, Unity' 'Java, Go, Python, Kotlin'
 'Java, Go, JavaScript | Html | Css, React, React Native' 'Python, Django'
 'Python, TensorFlow ' 'Java, Kotlin, JavaScript | Html | Css, React'
 'Java, Php, Go, Python, Kotlin, JavaScript | Html | Css, React'
 'Php, Python, Ruby, JavaScript | Html | Css, Angular'
 'Java, .Net, Python, Kotlin, C / C++, JavaScript | Html | Css, Angular, Flutter'
 'Java, .Net, Kotlin, Swift / Objective C' 'Scala' '.Net, Selenium'
 'Kotlin, Swift / Objective C, Flutter' 'Kotlin, C / C++'
 'React, Vue, Angular, Twig '
 'Php, JavaScript | Html | Css, React, Vue, React Native'
 'Python, JavaScript | Html | Css, Angular'
 '.Net, Python, Ruby, C / C++, JavaScript | Html | Css, React, Vue'
 '.Net, Python, React' 'Python, JavaScript | Html | Css, React, Vue'
 'Php, Go, Python, JavaScript | Html | Css'
 'Java, Kotlin, Swift / Objective C, JavaScript | Html | Css, React, Flutter'
 'Go, C / C++, Unreal' 'Vue, Angular, Flutter, React Native'
 'Php, JavaScript | Html | Css, React, Mysql' 'React Native, nodejs'
 'Java, .Net, Go, Kotlin, React, Vue' '.Net, Kotlin'
 '.Net, Python, JavaScript | Html | Css, React'
 'Php, Go, Python, React, Vue, Angular'
 'Ruby, JavaScript | Html | Css, Angular' '.Net, React, Flutter'
 '.Net, Go, Python' 'Sadece yazılım destek'
 'Java, .Net, Php, JavaScript | Html | Css, Vue, Angular'
 '.Net, React, React Native, Unity'
 '.Net, C / C++, JavaScript | Html | Css, React, Angular' 'NodeJs,NestJs'
 'Java, PL/SQL PRO C' 'Python, Tableau ' '.Net, Dart'
 'JavaScript | Html | Css, React, TypeScript' '.Net, Php, Angular'
 'Php, JavaScript | Html | Css, Flutter, Troia'
 'Java, Php, Python, Angular' 'Kotlin, Flutter'
 'Java, JavaScript | Html | Css, Jsf'
 'Java, Kotlin, JavaScript | Html | Css' 'Vue, Flutter'
 '.Net, C / C++, React'
 '.Net, Python, JavaScript | Html | Css, Vue, Flutter' 'Python, Bash'
 '.Net, NodeJs' 'Php, Go' 'C / C++, ARM Assembly'
 'JavaScript | Html | Css, Angular, Node.js' '.Net, Sql'
 'Java, JavaScript | Html | Css, React, Angular'
 'Java, Go, JavaScript | Html | Css'
 'JavaScript | Html | Css, React, Node '
 'Java, Swift / Objective C, React, React Native' 'Java, .Net, Kotlin'
 '.Net, Delphi' 'Sap' 'Java, Swift / Objective C' '.Net, Xamarin'
 'Php, Python, JavaScript | Html | Css, React, Vue, Angular'
 '.Net, Visual basic' '.Net, JavaScript | Html | Css, Abap'
 'React, Angular' '.Net, Go, Angular'
 'Java, Python, Swift / Objective C, JavaScript | Html | Css'
 'Network tools' '.Net, Winform' 'Java, .Net, JavaFx' 'Java, React Native'
 'Php, Go, JavaScript | Html | Css, Vue, Flutter, React Native'
 'React Native, Delphi' 'Nodejs' 'Elixir'
 'Java, Php, Go, JavaScript | Html | Css, Vue' 'Java, Sql, unix'
 'Python, Shell script' 'Python, JavaScript | Html | Css, Vue'
 'Devops araçları: docker terraform ansible kubrrnetes'
 'Java, .Net, Swift / Objective C' 'Vue, NodeJS' 'Flutter, Plsql'
 '.Net, JavaScript | Html | Css, ABAP, FIORI UI5'
 'Php, JavaScript | Html | Css, React, Vue, Angular, React Native'
 'Php, Python' 'Java, Python, Kotlin' '.Net, React, Vue, Angular, Flutter'
 'Php, Go, JavaScript | Html | Css' 'Java, Go, React'
 '.Net, JavaScript | Html | Css, React, Vue, Angular, Flutter'
 'JavaScript | Html | Css, React, Vue, Angular'
 '.Net, Swift / Objective C, Flutter, Unity' 'Go, JavaScript | Html | Css'
 'Soa' 'Swift / Objective C, C / C++' '.Net, Go, Vue'
 '.Net, JavaScript | Html | Css, Angular, Flutter'
 'Php, Go, JavaScript | Html | Css, React' 'Python, Angular'
 'Php, Python, JavaScript | Html | Css, React, Vue, React Native'
 'Php, Go, React, Vue' '.Net, JavaScript | Html | Css, Visual Basic'
 'Java, Python, React'
 'Java, Kotlin, Swift / Objective C, Vue, Angular, Flutter, Unity'
 'Java, Php, Python, Swift / Objective C, C / C++, JavaScript | Html | Css'
 'JavaScript | Html | Css, Node'
 'Php, Python, JavaScript | Html | Css, React'
 '.Net, Php, JavaScript | Html | Css, React'
 'Java, JavaScript | Html | Css, Hybris'
 'Java, Php, JavaScript | Html | Css, Angular' 'Java, .Net, Php'
 'Python, C / C++, JavaScript | Html | Css, React'
 'Php, JavaScript | Html | Css, React, Vue, NodeJS\\Typescript'
 'Python, Kotlin, Swift / Objective C' 'JavaScript | Html | Css, ABAP'
 'Ruby, JavaScript | Html | Css, Vue'
 'Php, Python, JavaScript | Html | Css' 'Java, Angular, Flutter'
 '.Net, Nodejs' 'Java, Scala'
 'Swift / Objective C, JavaScript | Html | Css, React, Flutter'
 'Go, Python, JavaScript | Html | Css' 'Python, scala' 'CS'
 'Java, .Net, C / C++, React' 'Swift / Objective C, Angular' 'Selenium'
 'JavaScript | Html | Css, Vue, Node , TS'
 'Java, .Net, JavaScript | Html | Css, React, Angular'
 'Java, .Net, Php, Swift / Objective C, JavaScript | Html | Css, Flutter'
 'Java, Python, Angular' 'JavaScript | Html | Css, Nodejs' 'Python, BASH'
 '.Net, Php, JavaScript | Html | Css, React, React Native' 'Abap' 'C#'
 'Ms Project, jira' 'Python, R, Matlab' 'Java, Flutter, React Native'
 'C / C++, Unity, Unreal'
 'Java, .Net, Php, JavaScript | Html | Css, React, Vue'
 'Java, .Net, C / C++, JavaScript | Html | Css, Angular'
 'Java, .Net, C / C++, Csharp' '.Net, Go, Kotlin'
 'Php, Go, Python, Swift / Objective C, JavaScript | Html | Css, React'
 '.Net, Kotlin, Angular' 'Abap fiori' 'Java, .Net, Go, Kotlin, React'
 '.Net, Php, Python, Ruby, C / C++'
 'Python, JavaScript | Html | Css, React, React Native'
 '.Net, JavaScript | Html | Css, C#   , Blazor '
 'C / C++, JavaScript | Html | Css' 'Unity, Unreal'
 'Java, .Net, Swift / Objective C, C / C++, JavaScript | Html | Css, Flutter'
 '.Net, Php, JavaScript | Html | Css, Vue, Flutter'
 'Java, .Net, Swift / Objective C, Vue, React Native'
 'JavaScript | Html | Css, React, GraphQL, NodeJs' '.Net, Go, node js'
 'Python, Sql' 'JavaScript | Html | Css, Vue, Nuxt.js'
 'Java, .Net, JavaScript | Html | Css, React, React Native'
 'Php, Go, Python, C / C++' 'SQL, QLIK' 'Java, Php, Go, Python' 'Bash'
 'Java, SQL' 'JavaScript | Html | Css, React, Vue, Angular, Threejs'
 'Java, Go, JavaScript | Html | Css, React'
 'Go, JavaScript | Html | Css, React'
 '.Net, JavaScript | Html | Css, Angular, DevExtreme'
 'JavaScript | Html | Css, React, Angular, nodejs'
 'C / C++, JavaScript | Html | Css, React' 'Ansible, bash'
 'Php, Python, Vue, Angular' '.Net, Python, React, Angular'
 'Php, JavaScript | Html | Css, Vue, Flutter'
 '.Net, JavaScript | Html | Css, React, Angular, React Native'
 'Visual Basic' 'Php, JavaScript | Html | Css, React, Vue, nodejs'
 '.Net, Python, JavaScript | Html | Css'
 'JavaScript | Html | Css, Troia, sql' 'Java, .Net, Vue, Angular'
 'Java, .Net, Python, C / C++, JavaScript | Html | Css, React Native'
 'Swift / Objective C, JavaScript | Html | Css, React, Vue, React Native'
 '.Net, Ruby, C / C++, JavaScript | Html | Css, Angular'
 'JavaScript | Html | Css, Rust'
 '.Net, JavaScript | Html | Css, React, Angular, Flutter'
 '.Net, Oracle forms,reports'
 'Php, JavaScript | Html | Css, React, React Native'
 'Php, Go, Python, JavaScript | Html | Css, Flutter, Unity'
 'Java, .Net, JavaScript | Html | Css, Angular'
 'Java, Php, Python, C / C++'
 '.Net, JavaScript | Html | Css, Vue, Flutter'
 '.Net, Php, JavaScript | Html | Css, Vue'
 'JavaScript | Html | Css, React, Angular, React Native'
 'Python, R, SQL, SSAS, SSRS, SSIS, Azure Cloud'
 'Python, C / C++, JavaScript | Html | Css'
 'Java, JavaScript | Html | Css, React, Vue'
 'Java, Kotlin, Swift / Objective C, React Native'
 'JavaScript | Html | Css, React, React Native, Nodejs'
 'Java, Go, Python, JavaScript | Html | Css, React, React Native'
 'Go, Python, C / C++' 'R + Power BI' 'NodeJS / TypeScript'
 'React, Angular, React Native' '.Net, Kotlin, React'
 'JavaScript | Html | Css, Coldfusion '
 'Java, .Net, Python, C / C++, React, React Native, Unreal'
 '.Net, Php, Go' 'Go, Swift / Objective C' nan
 'Java, .Net, Php, Python, C / C++, JavaScript | Html | Css'
 'Php, Go, Python' 'JavaScript | Html | Css, React, Node js'
 'Java, Php, Python' 'C / C++, matlab' 'Jdeveloper'
 'Java, .Net, Go, Python, C / C++, JavaScript | Html | Css, Angular, Flutter'
 'Php, JavaScript | Html | Css, Laravel codeigniter bootsrap jquery'
 'JavaScript | Html | Css, React, Vue, Angular, Flutter'
 'Java, .Net, Php, Go, Python, Ruby, Kotlin, Swift / Objective C, C / C++, JavaScript | Html | Css, React, Vue, Angular, Flutter, React Native, Unity, Unreal'
 'Linux' '.Net, JavaScript | Html | Css, React, Node'
 '.Net, Go, Kotlin, Swift / Objective C, Vue, Flutter'
 'Java, .Net, JavaScript | Html | Css, Mssql'
 'Python, C / C++, JavaScript | Html | Css, React, Bash'
 'Python, React, Angular' 'Python, Kotlin' '.Net, Python, Kotlin'
 'Java, Python, JavaScript | Html | Css, React, React Native'
 'React, Vue, Angular, React Native' 'Java, Python, Scala'
 'Java, .Net, JavaScript | Html | Css, Vue, Angular, Flutter' 'SQL '
 'Python, R' 'Php, Python, C / C++, JavaScript | Html | Css'
 '.Net, Angular, Flutter' 'Java, Php, Go' 'Python, React Native'
 'JavaScript | Html | Css, Flutter' 'Go, Vue'
 'Java, Php, JavaScript | Html | Css, React, Angular'
 'Php, Go, Python, Vue' 'Java, .Net, Python, C / C++, Angular'
 '.Net, JavaScript | Html | Css, Flutter, ABAP'
 'T-SQL,SSIS,SSAS,SSRS,Tableau'
 'Java, Kotlin, JavaScript | Html | Css, React, Vue'
 'Java, .Net, Php, Go, Python, Ruby, React'
 'JavaScript | Html | Css, pl/sql, oracle apex' '.Net, 1C Enterprise '
 'React Native, NodeJS' 'Ladder diagram' 'Java, Cobol '
 'Java, .Net, C / C++, Angular'
 'Java, .Net, JavaScript | Html | Css, Angular, Unity'
 'Java, .Net, React, Angular'
 'Java, .Net, Python, JavaScript | Html | Css, React, Flutter'
 'React, Flutter, React Native' 'sql' 'C / C++, Nginx '
 '.Net, C / C++, Pl/sql' 'Java, Go, Python, React'
 '.Net, Go, JavaScript | Html | Css, Typescript' 'Python, bash'
 'Php, JavaScript | Html | Css, React Native' 'Clojure' 'Test'
 'JavaScript | Html | Css, Pl-sql'
 'Php, Go, JavaScript | Html | Css, Angular'
 'JavaScript | Html | Css, node'
 'Java, Kotlin, Swift / Objective C, C / C++' 'Go, React' 'VB6.0'
 'Kotlin, Godot' '.Net, JavaScript | Html | Css, JQuery'
 'Swift / Objective C, Unity' 'Python, Swift / Objective C'
 '.Net, C / C++, Angular'
 'Go, JavaScript | Html | Css, React, Vue, Angular'
 '.Net, React, Vue, Angular' 'Php, React, React Native'
 'Php, JavaScript | Html | Css, React, Vue, Angular'
 'Java, Swift / Objective C, JavaScript | Html | Css, React'
 'C / C++, Unity' 'Go, C / C++, Flutter'
 'Java, .Net, JavaScript | Html | Css, React, Flutter' 'C / C++, Qt'
 '.Net, Python, Delphi' '.Net, Php, Python, Angular'
 'Java, Python, JavaScript | Html | Css, Vue'
 'Java, .Net, Swift / Objective C, JavaScript | Html | Css'
 'Ruby, Angular' 'Vue, Angular' '.Net, C / C++, JavaScript | Html | Css'
 'Java, .Net, Php, Python, C / C++, JavaScript | Html | Css, React, Angular, Flutter, Unity'
 'Java, C / C++, React' '.Net, Go, Node.js' 'Php, React Native'
 '.Net, Go, Kotlin, Swift / Objective C, JavaScript | Html | Css'
 'Flutter, g' 'Java, Python, C / C++, JavaScript | Html | Css, React'
 'Java, Php, Python, JavaScript | Html | Css, Vue' '.Net, React, Unity'
 'Java, Go, Kotlin, Swift / Objective C'
 'Go, Python, C / C++, JavaScript | Html | Css, React'
 'Java, Php, Python, React, Vue, Angular'
 'Php, Python, JavaScript | Html | Css, React, Angular' '.Net, Typescript'
 'Java, Python, Kotlin, JavaScript | Html | Css, React'
 'JavaScript | Html | Css, React, Next' 'C / C++, C#/.Net'
 'Java, Go, Kotlin, JavaScript | Html | Css, React, Angular'
 'Java, Php, Python, Kotlin, Swift / Objective C, JavaScript | Html | Css, React, Vue, React Native'
 'Java, JavaScript | Html | Css, NodeJs, typescript' 'Java, Php, Vue'
 'Python, JavaScript | Html | Css, Vue, Angular'
 'Java, JavaScript | Html | Css, Cobol'
 'Java, .Net, Python, Swift / Objective C, JavaScript | Html | Css'
 '.Net, Powershell' 'Java, .Net, Python, Kotlin'
 'Java, Python, JavaScript | Html | Css, Angular'
 '.Net, Swift / Objective C, React, Flutter, React Native'
 'K8s, terraform ' 'NodeJs'
 'Java, .Net, Php, Swift / Objective C, JavaScript | Html | Css, Angular'
 'Java, Python, Swift / Objective C, JavaScript | Html | Css, Flutter, React Native'
 'Python, SPSS Modeler' 'Java, Python, C / C++, Matlab, octave'
 '.Net, Kotlin, Swift / Objective C, JavaScript | Html | Css, React, React Native'
 '.Net, React Native' 'React, nextjs'

In [10]:
#birbiri ile alakalı ve az sayılı pozisyon tiplerini birleştirdik.Daha anlamlı sonuşlar almamız için bu işlemi yapıyoruz.
#DATA SCIENTIST POZİSYONU İLE ALAKALI OLANLAR
ds= ["Data Scientist", "Machine Learning", "Data Analyst", "Data Engineer", "Computer Vision Engineer"]
for j in ds:
    df[df["POSITION"] == j]
    for i in df[df["POSITION"] == j].index:
        df["POSITION"][i] = "DATA SCIENTIST"

In [11]:
# DATABASE ADMİN  İLE ALAKALI OLANLAR
for i in df[df["POSITION"]=="SAP/ABAP/ERP Developer"].index:
    df["POSITION"][i] = "DATABASE ADMIN"

for i in df[df["POSITION"]=="Database Administrator"].index:
    df["POSITION"][i] = "DATABASE ADMIN"

for i in df[df["POSITION"]=="SysAdmin"].index:
    df["POSITION"][i] = "DATABASE ADMIN"

In [12]:
#SAYILARI ÇOK AZ OLAN POZİSYONLAR
diger=["Project & Product Manager / PO", "Support Engineer", "Business Analyst", "RPA Developer", "IT Specialist", "R&D Engineer", "Security", "Consultant", "Seo Specialist", "Blockchain Developer"]
for j in diger:
    df[df["POSITION"] == j]
    for i in df[df["POSITION"] == j].index:
        df["POSITION"][i] = "OTHERS"

In [13]:
df.head()

,LEVEL,POSITION,TECH_STACK,EXPERIENCE,GENDER,COMPANY,COMPANY_SIZE,WORK_TYPE,CITY,CURRENCY,SALARY_FOR_OTHER_CURRENCY,SALARY_FOR_TL_CURRENCY
0,Middle,Back-end Developer,Php,3 - 5 Yıl,Erkek,Startup,25 - 50 Kişi,Hibrit (Ofis + Remote),İstanbul,₺ - Türk Lirası,NaN,15.000 TL - 15.999 TL
1,Junior,Front-end Developer,React,0 - 1 Yıl,Erkek,Startup,10 - 25 Kişi,Hibrit (Ofis + Remote),İstanbul,₺ - Türk Lirası,NaN,8.000 TL - 8.999 TL
2,Middle,Back-end Developer,.Net,1 - 3 Yıl,Erkek,Outsource,10 - 25 Kişi,Remote,İstanbul,₺ - Türk Lirası,NaN,15.000 TL - 15.999 TL
3,Junior,Full Stack Developer,"Java, JavaScript | Html | Css, React, React Na...",1 - 3 Yıl,Erkek,Startup,10 - 25 Kişi,Hibrit (Ofis + Remote),İstanbul,₺ - Türk Lirası,NaN,10.000 TL - 10.999 TL
4,Junior,Back-end Developer,".Net, JavaScript | Html | Css",0 - 1 Yıl,Erkek,Kurumsal,250+,Pandemi Nedeniyle; Geçici Olarak Hibrit (Ofis ...,Kocaeli,₺ - Türk Lirası,NaN,5.000 TL - 5.999 TL

In [14]:
#tüm pozisyon isimlendirmeleri standart hale gelsin diye büyük harf yaptık.
df["POSITION"] = [i.upper() for i in df["POSITION"]]

In [15]:
df["POSITION"].value_counts()

FULL STACK DEVELOPER              1442
BACK-END DEVELOPER                1290
FRONT-END DEVELOPER                578
MOBILE APPLICATION DEVELOPER       453
TEAM / TECH LEAD                   296
DATA SCIENTIST                     150
SOFTWARE DEVELOPMENT MANAGER       149
SOFTWARE ARCHITECT                 126
EMBEDDED SOFTWARE DEVELOPER        118
QA / TEST AUTOMATION DEVELOPER      96
DEVOPS ENGINEER                     96
GAME DEVELOPER                      89
OTHERS                              63
CTO                                 51
DATABASE ADMIN                      33
Name: POSITION, dtype: int64

In [16]:
df["WORK_TYPE"].value_counts()

Remote                                                     1960
Hibrit (Ofis + Remote)                                     1395
Ofis                                                        803
Pandemi Nedeniyle; Geçici Olarak Remote                     548
Pandemi Nedeniyle; Geçici Olarak Hibrit (Ofis + Remote)     324
Name: WORK_TYPE, dtype: int64

In [17]:
#okunaklılık için pandemi nedeniyle ibareleri silindi.
for i in df[df["WORK_TYPE"]=="Pandemi Nedeniyle; Geçici Olarak Hibrit (Ofis + Remote)"].index:
    df["WORK_TYPE"][i] = "Geçici Hibrit"

for i in df[df["WORK_TYPE"]=="Pandemi Nedeniyle; Geçici Olarak Remote"].index:
    df["WORK_TYPE"][i] = "Geçici Remote"

for i in df[df["WORK_TYPE"]=="Hibrit (Ofis + Remote)"].index:
    df["WORK_TYPE"][i] = "Hibrit"

In [18]:
df["WORK_TYPE"].value_counts()

Remote           1960
Hibrit           1395
Ofis              803
Geçici Remote     548
Geçici Hibrit     324
Name: WORK_TYPE, dtype: int64

In [19]:
df["COMPANY"].value_counts()

Kurumsal                   2463
Startup                    1152
E-Ticaret                   594
Outsource                   370
Dijital / Reklam Ajansı     146
Oyun                        104
Diğer                        91
Yazılım & Teknoloji          33
Fintech / Finans             18
Kamu                         16
Kobi                         14
Savunma & Güvenlik            8
Danışmanlık                   7
Telekomünikasyon              6
Banka                         5
kamu                          1
kobi                          1
diğer                         1
Name: COMPANY, dtype: int64

In [20]:
#SAYISI ÇOK AZ VEYA BENZER OLAN COMPANY KOLONLARINI BİRLEŞTİRDİK.
list_company= ["diğer", "kobi", "kamu", "Banka", "Telekomünikasyon","Danışmanlık","Savunma & Güvenlik","Kobi","Kamu","Diğer"]
for i in list_company:
    df[df["COMPANY"] == i]
    for j in df[df["COMPANY"] == i].index:
        df["COMPANY"][j] = "DIGER"

In [21]:
df["COMPANY"].value_counts()

Kurumsal                   2463
Startup                    1152
E-Ticaret                   594
Outsource                   370
DIGER                       150
Dijital / Reklam Ajansı     146
Oyun                        104
Yazılım & Teknoloji          33
Fintech / Finans             18
Name: COMPANY, dtype: int64

In [22]:
#TL OLAN MAAŞLARI DÜZENLİYORUZ.
num=[]

for item in df["SALARY_FOR_TL_CURRENCY"]:
    if item:
        num.append(str(item).split(" "))

In [23]:
#TL tipinden minimum maaş bilgilerini aldım.NaN ifadeler yerine 0 atadım.Değerleri doğru almak için 1000 ile çarptım
num1=[]
for i in range(0,len(num)):
    if num[i][0]=="nan":
        num1.append(0)
    else:
        num1.append(float(num[i][0])*1000)

In [24]:
#TL tipinden maximum maaş bilgilerini aldım,
# NaN ifadeler yerine 0 atadım, doğru değerleri elde etmek için 1000 ile çarptım.
# Max ve Min değerleri aynı olmasın diye içerisinde üzeri yazan değerlerin üst sınırını 60000 tl aldım.
num2=[]
for i in range(0,len(num)):
    if num[i][0]=="nan":
        num2.append(0)
    elif (num[i][3])=='üzeri':
        num2.append(60000.0)
    else:
        num2.append(float(num[i][3])*1000)

In [25]:
#veri setimize min tl ve max tl kazançlarını gösteren kolonları ekledik.
df["MIN_TL"]=num1

df["MAX_TL"]=num2

In [26]:
#TL dışındaki para birimlerini parçaladım.
cur=[]

for item in df["SALARY_FOR_OTHER_CURRENCY"]:
    if item:
        cur.append(str(item).split(" "))

In [27]:
#Döviz tipi min maaş bilgilerini çektim.1000 ile çarptım. yanlış girilen 1.0 YERİNE 1000 döviz birimini aynı bıraktım
cur1=[]
for i in range(0,len(cur)):
    if cur[i][0]=="nan":
        cur1.append(0)
    elif cur[i][0]=="1000":
        cur1.append(float(cur[i][0]))
    else:
        cur1.append(float(cur[i][0])*1000)

In [28]:
#Döviz tipi max maaş bilgilerini çektim.1000 ile çarptım. Üst sınırı 10999 kabul ettim.(TL de 60000 almıştım.)
cur2=[]
for i in range(0,len(cur)):
    if cur[i][0]=="nan":
        cur2.append(0)
    elif (cur[i][2])=='üzeri':
        cur2.append(10999)#float(cur[i][0])
    else:
        cur2.append(float(cur[i][2])*1000)

In [29]:
df["CUR_MIN"]=cur1
df["CUR_MAX"]=cur2

In [30]:
df.head()

,LEVEL,POSITION,TECH_STACK,EXPERIENCE,GENDER,COMPANY,COMPANY_SIZE,WORK_TYPE,CITY,CURRENCY,SALARY_FOR_OTHER_CURRENCY,SALARY_FOR_TL_CURRENCY,MIN_TL,MAX_TL,CUR_MIN,CUR_MAX
0,Middle,BACK-END DEVELOPER,Php,3 - 5 Yıl,Erkek,Startup,25 - 50 Kişi,Hibrit,İstanbul,₺ - Türk Lirası,NaN,15.000 TL - 15.999 TL,15000.0,15999.0,0.0,0.0
1,Junior,FRONT-END DEVELOPER,React,0 - 1 Yıl,Erkek,Startup,10 - 25 Kişi,Hibrit,İstanbul,₺ - Türk Lirası,NaN,8.000 TL - 8.999 TL,8000.0,8999.0,0.0,0.0
2,Middle,BACK-END DEVELOPER,.Net,1 - 3 Yıl,Erkek,Outsource,10 - 25 Kişi,Remote,İstanbul,₺ - Türk Lirası,NaN,15.000 TL - 15.999 TL,15000.0,15999.0,0.0,0.0
3,Junior,FULL STACK DEVELOPER,"Java, JavaScript | Html | Css, React, React Na...",1 - 3 Yıl,Erkek,Startup,10 - 25 Kişi,Hibrit,İstanbul,₺ - Türk Lirası,NaN,10.000 TL - 10.999 TL,10000.0,10999.0,0.0,0.0
4,Junior,BACK-END DEVELOPER,".Net, JavaScript | Html | Css",0 - 1 Yıl,Erkek,Kurumsal,250+,Geçici Hibrit,Kocaeli,₺ - Türk Lirası,NaN,5.000 TL - 5.999 TL,5000.0,5999.0,0.0,0.0

In [31]:
#bu işlemlerle kazanılan miktarı sayısal bir değişken yapmış olduk.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5030 entries, 0 to 5029
Data columns (total 16 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   LEVEL                      5030 non-null   object
 1   POSITION                   5030 non-null   object
 2   TECH_STACK                 5029 non-null   object
 3   EXPERIENCE                 5030 non-null   object
 4   GENDER                     5030 non-null   object
 5   COMPANY                    5030 non-null   object
 6   COMPANY_SIZE               5030 non-null   object
 7   WORK_TYPE                  5030 non-null   object
 8   CITY                       5030 non-null   object
 9   CURRENCY                   5030 non-null   object
 10  SALARY_FOR_OTHER_CURRENCY  533 non-null    object
 11  SALARY_FOR_TL_CURRENCY     4493 non-null   object
 12  MIN_TL                     5030 non-null   float64
 13  MAX_TL                     5030 non-null   float64
 14  CUR_MIN                    5030 non-null   float64
 15  CUR_MAX                    5030 non-null   float64
dtypes: float64(4), object(12)
memory usage: 628.9+ KB

In [32]:
#12 Aralık 2022 tarihli Sterlin Dolar ve Euro kurlarıyla Döviz cinsi TL ye çevrildi.
# >>>>Bu değerler 0 olan MIN_TL lere atandı.
#bu şekilde tüm maaş değerleri TL olarak kıyaslanabilecek noktasına geldik.
(df.loc[df["CURRENCY"]=="£ - Sterlin","MIN_TL"])=(df.loc[df["CURRENCY"]=="£ - Sterlin"]["CUR_MIN"]*22.56)
(df.loc[df["CURRENCY"]=="$ - Dolar","MIN_TL"])=(df.loc[df["CURRENCY"]=="$ - Dolar"]["CUR_MIN"]*18.63)
(df.loc[df["CURRENCY"]=="€ - Euro","MIN_TL"])=(df.loc[df["CURRENCY"]=="€ - Euro"]["CUR_MIN"]*19.47)

In [33]:
#BENZER İŞLEMİ MAX_TL İÇİN DE YAPIYORUZ
(df.loc[df["CURRENCY"]=="£ - Sterlin","MAX_TL"])=(df.loc[df["CURRENCY"]=="£ - Sterlin"]["CUR_MAX"]*22.56)+(df.loc[df["CURRENCY"]=="£ - Sterlin"]["MAX_TL"])
(df.loc[df["CURRENCY"]=="$ - Dolar","MAX_TL"])=(df.loc[df["CURRENCY"]=="$ - Dolar"]["CUR_MAX"]*18.63)+(df.loc[df["CURRENCY"]=="$ - Dolar"]["MAX_TL"])
(df.loc[df["CURRENCY"]=="€ - Euro","MAX_TL"])=(df.loc[df["CURRENCY"]=="€ - Euro"]["CUR_MAX"]*19.47)+(df.loc[df["CURRENCY"]=="€ - Euro"]["MAX_TL"])

In [34]:
df.head()

,LEVEL,POSITION,TECH_STACK,EXPERIENCE,GENDER,COMPANY,COMPANY_SIZE,WORK_TYPE,CITY,CURRENCY,SALARY_FOR_OTHER_CURRENCY,SALARY_FOR_TL_CURRENCY,MIN_TL,MAX_TL,CUR_MIN,CUR_MAX
0,Middle,BACK-END DEVELOPER,Php,3 - 5 Yıl,Erkek,Startup,25 - 50 Kişi,Hibrit,İstanbul,₺ - Türk Lirası,NaN,15.000 TL - 15.999 TL,15000.0,15999.0,0.0,0.0
1,Junior,FRONT-END DEVELOPER,React,0 - 1 Yıl,Erkek,Startup,10 - 25 Kişi,Hibrit,İstanbul,₺ - Türk Lirası,NaN,8.000 TL - 8.999 TL,8000.0,8999.0,0.0,0.0
2,Middle,BACK-END DEVELOPER,.Net,1 - 3 Yıl,Erkek,Outsource,10 - 25 Kişi,Remote,İstanbul,₺ - Türk Lirası,NaN,15.000 TL - 15.999 TL,15000.0,15999.0,0.0,0.0
3,Junior,FULL STACK DEVELOPER,"Java, JavaScript | Html | Css, React, React Na...",1 - 3 Yıl,Erkek,Startup,10 - 25 Kişi,Hibrit,İstanbul,₺ - Türk Lirası,NaN,10.000 TL - 10.999 TL,10000.0,10999.0,0.0,0.0
4,Junior,BACK-END DEVELOPER,".Net, JavaScript | Html | Css",0 - 1 Yıl,Erkek,Kurumsal,250+,Geçici Hibrit,Kocaeli,₺ - Türk Lirası,NaN,5.000 TL - 5.999 TL,5000.0,5999.0,0.0,0.0

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5030 entries, 0 to 5029
Data columns (total 16 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   LEVEL                      5030 non-null   object
 1   POSITION                   5030 non-null   object
 2   TECH_STACK                 5029 non-null   object
 3   EXPERIENCE                 5030 non-null   object
 4   GENDER                     5030 non-null   object
 5   COMPANY                    5030 non-null   object
 6   COMPANY_SIZE               5030 non-null   object
 7   WORK_TYPE                  5030 non-null   object
 8   CITY                       5030 non-null   object
 9   CURRENCY                   5030 non-null   object
 10  SALARY_FOR_OTHER_CURRENCY  533 non-null    object
 11  SALARY_FOR_TL_CURRENCY     4493 non-null   object
 12  MIN_TL                     5030 non-null   float64
 13  MAX_TL                     5030 non-null   float64
 14  CUR_MIN                    5030 non-null   float64
 15  CUR_MAX                    5030 non-null   float64
dtypes: float64(4), object(12)
memory usage: 628.9+ KB

In [36]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
MIN_TL,5030.0,22662.206759,27404.429428,0.0,10000.0,15000.0,24000.0,225600.00
MAX_TL,5030.0,25691.419153,31744.874859,0.0,10999.0,15999.0,24999.0,248137.44
CUR_MIN,5030.0,430.218688,1534.452668,0.0,0.0,0.0,0.0,10000.00
CUR_MAX,5030.0,536.076938,1793.810349,0.0,0.0,0.0,0.0,10999.00

In [37]:
#maaş bilgisi hiç girilmemiş kişileri sildik.
df=df.drop(df.loc[df["MIN_TL"]==df["MIN_TL"].min()].index)

In [38]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
MIN_TL,5026.0,22680.242738,27407.871564,5000.0,10000.0,15000.0,24000.0,225600.00
MAX_TL,5026.0,25711.865965,31749.227207,5999.0,10999.0,15999.0,24999.0,248137.44
CUR_MIN,5026.0,430.561082,1535.015246,0.0,0.0,0.0,0.0,10000.00
CUR_MAX,5026.0,536.503581,1794.460372,0.0,0.0,0.0,0.0,10999.00

In [39]:

#df.to_csv("step1.csv")